### ISSUE TITLE
Chrome Extension - Warning does not appear

### ISSUE THREAD

**Issue by corvec** [aido179/zwBlocker#2] opened 2018-04-16 16:30 UTC
I installed the extension from the Chrome Web Store on Chrome 65.0.3325.181 on a MBP running macOS Sierra (10.12.6). I've verified this behavior with my normal extensions and in Incognito mode with no other extensions enabled. Its current behavior is as follows:

* Plugin icon displays some number that may or may not be correct. Most pages are showing 99+. https://umpox.github.io/zero-width-detection/ shows 9.
* When selecting text that I know to have zero-width character in it, I don't get a warning of any kind.
* When left-clicking on the Github / Twitter links in the extension's window after clicking on the icon, nothing happens (the page does not load). Middle-clicking or right-clicking and clicking on "Open in..." allows me to open the links in a new tab, though.

**Comment by aido179** [comment] 2018-04-16 21:34
Thanks for the response. 

1. Duplicate of [this issue](https://github.com/aido179/zwBlocker/issues/1).
2. Can you post which character isn't being detected? The detection function is fairly naive - and will more than likely need improvement over time.
3. Thanks - will figure that out asap.

**Comment by aido179** [comment] 2018-04-17 10:39
Fixed third part of your issue in 82421a011fdfc3c42fca5375398dc3e7e3afc764

Please create another issue for specific characters that are not detected.

**Closed as completed by aido179** 2018-04-17 10:39 UTC
